common: &common
  adapter: postgresql
  host: localhost
  port: 5432
  username: rails
  password: password

development:
  database: rails_rspec_development
  <<: *common

test:
  database: rails_rspec_test
  <<: *common

production:
  database: rails_rspec_production
  <<: *common

