common: &common
  adapter: postgresql
  host: localhost
  port: 5432

development:
  <<: *common
  database: rails_mvc_development

test:
  <<: *common
  database: rails_mvc_test

production:
  <<: *common
  database: rails_mvc_production

